/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 earth.gltf 
Author: OSCAR CREATIVO (https://sketchfab.com/oscar_creativo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/eye-free-model-3d-by-oscar-creativo-5d466ea41c874fc5b376c92a313a9bb3
Title: EYE FREE MODEL 3D BY Oscar creativo
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/earth.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.CORNEA__CORNEA__0.geometry} material={materials.CORNEA} />
      <mesh geometry={nodes.IRIS_FINAL_IRIS_FINAL_0.geometry} material={materials.IRIS_FINAL} />
    </group>
  )
}

useGLTF.preload('/earth.gltf')
