/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: Wian Z (https://sketchfab.com/Vickocuy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/simple-model-rapper-concert-970ee4873d84489ca34f54eb0c6c102b
Title: Simple Model Rapper Concert
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Merged_base_copy2_4_Merged_base_copy2_40_0.geometry} material={materials.Merged_base_copy2_40} />
      <mesh geometry={nodes.Merged_base_copy2_4_Merged_base_copy2_40_0_1.geometry} material={materials.Merged_base_copy2_40} />
      <mesh geometry={nodes.Merged_base_copy2_4_Merged_base_copy2_40_0_2.geometry} material={materials.Merged_base_copy2_40} />
      <mesh geometry={nodes.Merged_base_copy2_4_Merged_base_copy2_41_0.geometry} material={materials.Merged_base_copy2_41} />
      <mesh geometry={nodes.Merged_base_copy2_4_Merged_base_copy2_41_0_1.geometry} material={materials.Merged_base_copy2_41} />
      <mesh geometry={nodes.Merged_base_copy2_4_Merged_base_copy2_41_0_2.geometry} material={materials.Merged_base_copy2_41} />
      <mesh geometry={nodes.Merged_base_copy2_4_Merged_base_copy2_41_0_3.geometry} material={materials.Merged_base_copy2_41} />
      <mesh geometry={nodes.Merged_base_copy2_4_Merged_base_copy2_42_0.geometry} material={materials.Merged_base_copy2_42} />
      <mesh geometry={nodes.Merged_base_copy2_4_Merged_base_copy2_42_0_1.geometry} material={materials.Merged_base_copy2_42} />
      <mesh geometry={nodes.Merged_base_copy2_4_Merged_base_copy2_42_0_2.geometry} material={materials.Merged_base_copy2_42} />
      <mesh geometry={nodes.Merged_base_copy2_4_Merged_base_copy2_42_0_3.geometry} material={materials.Merged_base_copy2_42} />
      <mesh geometry={nodes.Merged_base_copy2_4_Merged_base_copy2_43_0.geometry} material={materials.Merged_base_copy2_43} />
      <mesh geometry={nodes.Merged_base_copy2_4_Merged_base_copy2_43_0_1.geometry} material={materials.Merged_base_copy2_43} />
      <mesh geometry={nodes.Merged_base_copy2_4_Merged_base_copy2_43_0_2.geometry} material={materials.Merged_base_copy2_43} />
      <mesh geometry={nodes.Merged_base_copy2_4_Merged_base_copy2_43_0_3.geometry} material={materials.Merged_base_copy2_43} />
      <mesh geometry={nodes.Merged_base_copy2_4_Merged_base_copy2_43_0_4.geometry} material={materials.Merged_base_copy2_43} />
      <mesh geometry={nodes.Merged_base_copy2_4_Merged_base_copy2_43_0_5.geometry} material={materials.Merged_base_copy2_43} />
      <mesh geometry={nodes.Merged_base_copy2_4_Merged_base_copy2_43_0_6.geometry} material={materials.Merged_base_copy2_43} />
      <mesh geometry={nodes.Merged_base_copy2_4_Merged_base_copy2_43_0_7.geometry} material={materials.Merged_base_copy2_43} />
      <mesh geometry={nodes.Merged_base_copy2_4_Merged_base_copy2_43_0_8.geometry} material={materials.Merged_base_copy2_43} />
      <mesh geometry={nodes.Merged_base_copy2_4_Merged_base_copy2_43_0_9.geometry} material={materials.Merged_base_copy2_43} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
